theme: Jekyll-theme-minima
# At the top of the file
title: Vented Thoughts
description: My blog of unfiltered thoughts
theme: minima

# This line lets Jekyll know you’re overriding CSS
sass:
  style: compressed

# Tells it to use your custom SCSS
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"


/* General page background and text color */
body {
  background-color: #0b2e13; /* dark green background */
  color: #d3d3d3; /* white text */
  font-family: 'Times New Roman', sans-serif;
  line-height: 1.6;
  margin: 0;
  padding: 0;
}

/* Headings: lighter army green */
h1, h2, h3 {
  color: #4b6f44; /* army green headings */
  font-family: 'Georgia', serif;
}

/* Paragraphs */
p {
  margin-bottom: 1em;
}

/* Links */
a {
  color: #4b6f44; /* army green links */
  text-decoration: underline;
}

a:hover {
  color: #c0c0c0; /* light grey on hover */
  text-decoration: none;
}

/* Blockquotes */
blockquote {
  border-left: 4px solid #4b6f44; /* army green border */
  padding-left: 1em;
  color: #a9a9a9; /* grey text for blockquotes */
  font-style: italic;
}

/* Code blocks (if used) */
code, pre {
  background-color: #1a1a1a; /* near-black background for code */
  color: #d3d3d3;
  padding: 0.2em 0.4em;
  border-radius: 4px;
}

/* Selection color (highlight when text is selected) */
::selection {
  background: #4b6f44; /* army green highlight */
  color: #000;
}

/* Footer or smaller text (if you have it) */
small {
  color: #888; /* muted grey for less important text */
}
