theme: minimal 
title: Vented Thoughts
description: My blog of unfiltered thoughts

minimal:
  skin: custom

sass:
  style: compressed

header_pages:
  - index.md
  - thoughts.md
  - opinions.md
  - rants.md
